### ISSUE TITLE
PreviewJs failed installing npm dependencies

### ISSUE THREAD

**Issue by sagark1510** [fwouts/previewjs#408]
### Describe the bug

I tried installing and it didn't work. 

### Reproduction

1. go to vs code and search for extension
2. tap on install button
3. check on the output console

### Preview.js version

v1.5.1

### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 2.05 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.2 - /usr/local/opt/node@12/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/opt/node@12/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Nano: 2.0.6 - /usr/bin/nano
    VSCode: 1.66.0 - /usr/local/bin/code
    Vim: 8.2 - /usr/bin/vim
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Browsers:
    Chrome: 100.0.4896.60
    Firefox: 98.0.1
    Safari: 15.0
```

### Used Package Manager

npm

### Extension logs (useful for crashes)

```shell
Please wait while Preview.js installs dependencies. This could take a minute.

Dependencies will be installed in: /Users/sagarkhatri/.vscode/extensions/zenclabs.previewjs-1.5.1/dist/installed

$ npm install


Oh no, it looks like installation failed!

Error: Command failed with ENOENT: npm install
spawn npm ENOENT
```

**Comment by fwouts** [comment]
Hi @sagark1510, do you have NPM installed?

For context, Preview.js runs `npm install` when it first runs in order to install its dependencies (some of them are platform-specific so they can't be bundled in the extension).

If you didn't have NPM installed yet, do that and make sure to quit VS Code and reopen it before trying again. Hopefully that fixes it!

**Comment by jamesnw** [comment]
I also encountered the same error. I have npm installed. I've uninstalled/reinstalled Preview.js, and have restarted VS Code. I see the "P" icon, but when I click it, I get a toast that says "command 'previewjs.open' not found".

```
➜  / node --version
v14.17.6
➜  / npm --version
6.14.15
```

I do use `nvm` to manage `npm`.

**Comment by fwouts** [comment]
Thanks for the useful info @jamesnw!

What shell do you use? Is npm available in your default shell?

**Comment by jamesnw** [comment]
I use zsh by default. Npm is available in zsh and bash.

**Comment by fwouts** [comment]
@jamesnw I was able to reproduce it! The issue is that you're using npm v6, when the lockfile I bundled into the extension was generated using npm v7, and they're incompatible.

I'll try to push a fix, in the meantime if you want to address it:
- delete Preview.js entirely `rm -rf .vscode/extensions/zenclabs.previewjs-1.5.1` (uninstalling in VS Code doesn't appear to be sufficient)
- upgrade npm: `npm install -g npm`
- reinstall Preview.js

I'll update this thread when I've pushed a proper fix :)

**Comment by fwouts** [comment]
I've just released v1.5.2 for VS Code, let me know if it improves!

**Comment by jamesnw** [comment]
Thanks! I can confirm that the error message is showing as expected. My projects are stuck on npm 6 for now due to the incompatibility you mention, but hopefully I can update soon and check this out!

**Comment by fwouts** [comment]
I see, sorry to hear that! You could also upgrade temporarily just to install Preview.js, then downgrade back to 6.
