### ISSUE TITLE
Better JetBrain docs

### ISSUE THREAD

**Issue by Tumulte** [fwouts/previewjs#443]
I've installed previewJS and I can't find how to run the plugin in PHPstorm and the docs are solely VScode oriented

Just a basic "how to display the preview" for jetbrain product's is really needed

Best

**Comment by fwouts** [comment]
Thanks @Tumulte, appreciate the feedback!

I didn't document it for JetBrains because it looks pretty much exactly the same as on VS Code (inline link appearing above the component definition), but it sounds like that's not happening in your project 😢 

I agree that JetBrains isn't as well documented, I'll make sure to add some docs. I haven't tested with PHPStorm, only IntelliJ and WebStorm.

Do you see a "Preview.js logs" bottom panel at least, when you open a .js/.jsx/.tsx/.vue file?
![Screen Shot 2022-04-11 at 7 30 36 pm](https://user-images.githubusercontent.com/772570/162709978-03383807-6b3a-4930-b280-0e0ca4ae7da1.png)

**Comment by nmitic** [comment]
Same here, I am not able to see Preview.js tab :(

I am trying to pitch the idea of using preview js in my team, but not all of them (including myself) are using VS code.

Could it be that there is something which needs to be enabled in webstorm settings? I just switched from VS code to webstorm, kinda noob myself.

**Comment by fwouts** [comment]
Thanks for confirming, looks like there's a serious bug somewhere.

Would either of you (ideally both) be able to share your environment info?

Just run `npx envinfo --system --binaries --ides --browsers` :)

**Comment by nmitic** [comment]
Ofc, here it is 👍 
```
  System:
    OS: macOS 12.1
    CPU: (10) x64 Apple M1 Pro
    Memory: 31.39 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
    npm: 6.14.15 - /opt/homebrew/bin/npm
  IDEs:
    Nano: 2.0.6 - /usr/bin/nano
    VSCode: 1.65.2 - /usr/local/bin/code
    Vim: 8.2 - /usr/bin/vim
    WebStorm: 2021.3.2
    Xcode: /undefined - /usr/bin/xcodebuild
  Browsers:
    Chrome: 100.0.4896.75
    Safari: 15.2

**Comment by fwouts** [comment]
Cheers!

Preview.js should normally give you a friendly error if it detects that you have npm 6 or earlier:
![Screen Shot 2022-04-11 at 8 57 50 pm](https://user-images.githubusercontent.com/772570/162726213-37658cf6-aad6-4b89-b728-3a0f21498e81.png)

It looks like that hasn't happened in your case, sadly. It's possible that it will start working if you uninstall the plugin, upgrade to npm 7 or 8, then reinstall the plugin.

I'll see if I can manage to reproduce this on my end as well. Definitely not ideal!

**Comment by nmitic** [comment]
Thanks for taking a look at it.

After updating npm to the latest 8.6.0 and re installing, **_the previewJS tab is there._**

Now the things is that the latest version introduce different ways of handling peer dependencies and we have some issues using latest npm because of it. This kinda sucks, as I will have to move back to the version before npm 7 😢 

Here >> https://github.com/npm/feedback/discussions/191

**Comment by nmitic** [comment]
Sweet! Good luck and thanks, love the plugin btw 👌

**Comment by fwouts** [comment]
Hi @nmitic, the latest version v1.6.1 should now work with npm 6. Would you mind trying it out?

**Comment by fwouts** [comment]
@Tumulte I've added a JetBrains page here: https://previewjs.com/docs/platforms/jetbrains

**Comment by Tumulte** [comment]
So it's not a documentation problem... it just doesn't appear in the tool menu or tabs  

System:
    OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 262.55 MB / 15.33 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Managers:
    Apt: 2.0.6 - /usr/bin/apt
  Utilities:
    Make: 4.2.1 - /usr/bin/make
    Git: 2.25.1 - /usr/bin/git
  Virtualization:
    Docker: 20.10.15 - /usr/bin/docker
  IDEs:
    Nano: 4.8 - /usr/bin/nano
    Sublime Text: 4126 - /snap/bin/subl
    Vim: 8.1 - /usr/bin/vim
  Languages:
    Bash: 5.0.17 - /usr/bin/bash
    Perl: 5.30.0 - /usr/bin/perl
    Python: 2.7.18 - /usr/bin/python
    Python3: 3.8.10 - /usr/bin/python3
  Browsers:
    Chrome: 101.0.4951.54
    Firefox: 100.0
